version: '2'
services:
  enduser:
    image: rancher/lb-service-haproxy:v0.7.15
    stdin_open: true
    tty: true
    ports:
    - 443:443/tcp
    - 80:80/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: role_enduser_lb=true
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
  admin:
    image: rancher/lb-service-haproxy:v0.7.15
    stdin_open: true
    tty: true
    ports:
    - 443:443/tcp
    - 80:80/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: role_admin_lb=true
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
