version: '2'
services:
  metricbeat:
    scale: 1
    metadata:
      metricbeat-config: |
        metricbeat.config.modules:
          reload.period: 10s
          reload.enabled: false
        metricbeat.modules:
        - module: system
          metricsets:
            - cpu
            - load
            - filesystem
            - fsstat
            - memory
            - network
            - process
          enabled: true
          period: 10s
          processes: ['.*']
        output.kafka:
          hosts: ["kafka.kafka:9092"]
          topic: processtopic
          partition.round_robin:
            reachable_only: false
          required_acks: 1
          compression: gzip
          max_message_bytes: 1000000
        logging.to_files: false
