version: '2'
services:
  kibana:
    environment:
      ELASTICSEARCH_USERNAME: "{{ elasticsearch_svckibana_username }}"
      ELASTICSEARCH_PASSWORD: "{{ elasticsearch_svckibana_password }}"
      ELASTICSEARCH_URL: http://elasticsearch:9200
    external_links:
    - elasticsearch/elasticsearch-client:elasticsearch
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_soft_ne: role=tools
      io.rancher.scheduler.affinity:host_label_soft: role_kibana=true
    tty: true
    image: {{docker_elastic_repo}}/kibana/kibana:{{elasticsearch_version}}
    stdin_open: true
    ports:
    - 5601:5601

  kibana-setup:
    environment:
      SERVICE_ELASTICSEARCH_USERNAME: "{{elasticsearch_svckibana_username}}"
      SERVICE_ELASTICSEARCH_PASSWORD: "{{elasticsearch_svckibana_password}}"
      ELASTICSEARCH_VERSION: "{{elasticsearch_version}}"
      DEFAULT_INDEX_PATTERN: "{{elasticsearch_cluster_name}}-*"
    external_links:
    - elasticsearch/elasticsearch-client:elasticsearch
    image: adopteunops/kibana-rancher-setup:0.1.4
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: true
    tty: true
    stdin_open: true